kumuluzee:
  name: smartarticle-instituions
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/InstitutionsDS
      connection-url: jdbc:postgresql://159.122.187.161:31463/institution
      username: dbuser
      password: postgres
      max-pool-size: 20
  config:
    etcd:
      hosts: http://159.122.187.161:32428
    discovery:
      etcd:
        hosts: http://159.122.187.161:32428
app-properties:
  external-services:
    enabled: true