apiVersion: apps/v1
kind: Deployment
metadata:
  name: institution-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: institution-db
  template:
    metadata:
      labels:
        app: institution-db
    spec:
      containers:
      - image: postgres:10.5
        name: institution-db
        env:
        - name: POSTGRES_USER
          value: dbuser
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: institution
        ports:
        - containerPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: institution-db
spec:
  type: NodePort
  ports:
  - port: 5432
  selector:
    app: institution-db