apiVersion: apps/v1
kind: Deployment
metadata:
  name: institution-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: institution
  template:
    metadata:
      labels:
        app: institution
    spec:
      containers:
      - image: ajugo/smartarticle-institutions:0.2
        name: institution
        env:
        - name: KUMULUZEE_DISCOVERY_CLUSTER
          value: gcloud
        - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_CONFIG_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
          value: jdbc:postgresql://institution-db:5432/institution
        - name: KUMULUZEE_SERVER_BASEURL
          value: http://35.240.79.227:8081
        - name: KUMULUZEE_DATASOURCES0_USERNAME
          value: dbuser
        - name: KUMULUZEE_DATASOURCES0_PASSWORD
          value: postgres
        ports:
        - containerPort: 8081
          name: server
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: institution
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: institution